/* Browser verification against a temporary, loopback-only static server.
 * Requires Playwright and an installed Chromium-compatible browser.
 * No target scanning or external tool operation.
 */
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../site');
const playwright=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const types={'.html':'text/html','.js':'application/javascript','.json':'application/json','.svg':'image/svg+xml','.css':'text/css','.png':'image/png'};
const server=http.createServer((req,res)=>{let name;try{name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400).end();return;}const file=path.resolve(root,'.'+(name.endsWith('/')?name+'index.html':name));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,bytes)=>{if(err){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(bytes);});});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const proxyURL=process.env.CYBER_VERIFY_PROXY?new URL(process.env.CYBER_VERIFY_PROXY):null;
 browser=await playwright.chromium.launch({executablePath:process.env.CYBER_BROWSER_PATH||undefined,args:process.env.CYBER_BROWSER_PATH?['--no-sandbox','--single-process','--disable-gpu']:[],proxy:proxyURL?{server:proxyURL.origin,username:proxyURL.username||undefined,password:proxyURL.password||undefined,bypass:'127.0.0.1,localhost'}:undefined});
 const page=await browser.newPage({viewport:{width:1440,height:1080},ignoreHTTPSErrors:Boolean(proxyURL)});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 // Optional recorded PUBLIC image bytes make visual QA independent of proxy
 // subresource behavior. The site's published URLs and production code do not change.
 if(process.env.CYBER_IMAGE_FIXTURES){const images=JSON.parse(fs.readFileSync(process.env.CYBER_IMAGE_FIXTURES,'utf8'));await page.route('**/*',route=>{const file=images[route.request().url()];return file?route.fulfill({status:200,contentType:types[path.extname(file)]||'image/png',body:fs.readFileSync(file)}):route.continue();});}
 const screenshotDir=path.resolve(process.env.CYBER_SCREENSHOT_DIR||'/tmp/nightshift-screenshots');fs.mkdirSync(screenshotDir,{recursive:true});
 await page.goto(origin);assert.match(await page.title(),/NIGHTSHIFT/);assert.equal(await page.locator('nav a').count(),8);assert.equal(await page.locator('main h1').innerText(),'Cyberengineering,\nafter hours.');
 await page.locator('.screen-wall').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.screen-wall img')].every(i=>i.complete&&i.naturalWidth>0),null,{timeout:6000}).catch(async e=>{console.log(await page.locator('.screen-wall img').evaluateAll(a=>a.map(i=>({src:i.src,loaded:i.complete,width:i.naturalWidth}))));throw e;});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(screenshotDir,'profile-desktop.png')});
 await page.locator('#note').fill('Browser verification: fictional local note.');await page.locator('#save-note').click();await page.reload();assert.equal(await page.locator('#note').inputValue(),'Browser verification: fictional local note.');await page.locator('#clear-note').click();
 await page.goto(origin+'/missions.html');await page.waitForFunction(()=>document.querySelectorAll('#mission-cards .card').length===180);await page.locator('#search').fill('firmware');const missionFiltered=await page.locator('.card:visible').count();assert(missionFiltered>0&&missionFiltered<180);await page.locator('#search').fill('no-such-mission-xyz');assert.equal(await page.locator('.card:visible').count(),0);assert.match(await page.locator('#result-count').innerText(),/0 results/);
 await page.goto(origin+'/talks.html');await page.waitForFunction(()=>document.querySelectorAll('#talk-cards .card').length===32);await page.locator('#kind').selectOption('Workshop');assert.equal(await page.locator('.card:visible').count(),6);await page.locator('#kind').selectOption('');await page.locator('.card button').first().click();await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#talk-cards .card').length===32);await page.locator('#kind').selectOption('bookmarked');assert.equal(await page.locator('.card:visible').count(),1);await page.locator('.card:visible button').click();assert.equal(await page.locator('.card:visible').count(),0);
 await page.goto(origin+'/tools.html');assert.equal(await page.locator('.card').count(),20);await page.locator('#search').fill('curl');assert.equal(await page.locator('.card:visible').count(),1);
 await page.goto(origin+'/community.html');assert.equal(await page.locator('.credit').count(),15);
 await page.goto(origin+'/hardware.html');assert.equal(await page.locator('.device').count(),7);for(const image of await page.locator('.device .photo img').all()){await image.scrollIntoViewIfNeeded();await image.evaluate(i=>new Promise((resolve,reject)=>{if(i.complete){i.naturalWidth?resolve():reject(Error('Device image unavailable'));}else{i.addEventListener('load',resolve,{once:true});i.addEventListener('error',()=>reject(Error('Device image unavailable')),{once:true});}}));}await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(screenshotDir,'hardware-desktop.png'),fullPage:true});
 await page.goto(origin+'/reader.html?doc=foundations/TOOLS.md');await page.waitForSelector('#document h1');assert.match(await page.locator('#document').innerText(),/Tool field guide/);assert.equal(await page.locator('#document h3').count(),20);await page.screenshot({path:path.join(screenshotDir,'tool-guide.png')});
 await page.goto(origin+'/reader.html?doc=research/missions/001.md');await page.waitForSelector('#document h1');assert((await page.locator('#document').innerText()).length>1500);assert((await page.locator('#document a').count())>0);
 await page.goto(origin+'/reader.html?doc=does-not-exist.md');await page.waitForFunction(()=>document.querySelector('#reader-status').textContent.includes('not in the site'));
 await page.goto(origin+'/gallery.html');assert.equal(await page.locator('main figure').count(),26);await page.waitForFunction(()=>[...document.querySelectorAll('img[src^="media/"]')].every(i=>i.complete&&i.naturalWidth>0));
 await page.setViewportSize({width:390,height:844});for(const route of ['index','learn','tools','hardware','missions','talks','community','gallery']){await page.goto(origin+'/'+route+'.html');const width=await page.evaluate(()=>({view:innerWidth,body:document.documentElement.scrollWidth}));assert(width.body<=width.view+1,JSON.stringify({route,...width}));}
 await page.goto(origin);await page.screenshot({path:path.join(screenshotDir,'profile-mobile.png'),fullPage:true});await page.locator('#theme').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('light')));await page.reload();assert(await page.locator('body').evaluate(e=>e.classList.contains('light')));
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,desktop:[1440,1080],mobile:[390,844],missions:180,sessionRecords:32,tools:20,credits:15,hardwareEntries:7,pageErrors:errors,checks:['navigation','filters and empty states','bookmark persistence and removal','note persistence and clearing','document rendering','missing-document message','local diagram loading','eight mobile routes without overflow','theme persistence'],screenshotDir},null,2));
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});
